name: DIY Steward

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

concurrency: steward

jobs:
  steward:
    runs-on: ubuntu-latest
    name: DIY Steward
    steps:
      - uses: sbt/setup-sbt@v1
    
      - uses: actions/checkout@v6
          
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: 342893
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          author-email: 135588411+toniogela-s-scala-steward[bot]@users.noreply.github.com
          author-name: "TonioGela's Scala Steward[bot]"
          repos-file: 'repos.md'
